"""add eventos_excecoes

Revision ID: 3bdd133fbb6c
Revises: 2fbdb95bcf2c
Create Date: 2026-05-14 01:21:30.996061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdd133fbb6c'
down_revision: Union[str, None] = '2fbdb95bcf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_excecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_recorrente_id', sa.Integer(), nullable=False),
    sa.Column('data_original', sa.DateTime(), nullable=False, comment='Data/hora da ocorrência original que está sendo cancelada ou remarcada'),
    sa.Column('tipo', sa.Enum('CANCELAMENTO', 'REMARCACAO', name='excecaotipo'), nullable=False),
    sa.Column('data_nova', sa.DateTime(), nullable=True),
    sa.Column('hora_nova_inicio', sa.Time(), nullable=True),
    sa.Column('hora_nova_fim', sa.Time(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evento_recorrente_id'], ['eventos_recorrentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_excecoes')
    # ### end Alembic commands ###
